### ISSUE TITLE
 The keyboard clicking via yellow alphabets doesn’t work inside any of the mac applications

### ISSUE THREAD

**Issue by SandeepJoel** [dexterleng/homerow#25] opened 2022-12-31 08:56 UTC
For some unknown reasons, the keyboard clicking via yellow alphabets doesn’t work inside any of the mac applications. But it works in mac top menubar.
For example: In the below video I am not able to select numbered list option in slack reply box, after pressing `cmd-shift-space`.

**Other Details:**
Machine: Macbook pro 16inch 2019
OS: Monterey

https://user-images.githubusercontent.com/9314305/210131067-47b8e0c7-b92f-4c2c-a9c3-c44ccff01b65.mp4

**Comment by dexterleng** [comment] 2022-12-31 12:52
@SandeepJoel around the 21s mark you focused the numbered list button, did you press Enter? I didn't see the click animation.

**Comment by SandeepJoel** [comment] 2022-12-31 13:02
@dexterleng Yes I pressed enter, but the numbered list was not created.

**Comment by dexterleng** [comment] 2022-12-31 13:17
@SandeepJoel so when you hit Enter (1) the click doesn't happen (2) there is no click animation (3) the search bar input doesn't close itself and (3) the search input clears itself?

**Comment by dexterleng** [comment] 2023-01-09 05:27
@SandeepJoel did you manage to resolve this?

**Comment by SandeepJoel** [comment] 2023-01-09 05:37
No... the issue still exists @dexterleng

**Comment by gerardjanssen** [comment] 2023-01-25 13:41
I have the same issue. Homerow is not responding to the letters I enter in the search box

**Comment by gerardjanssen** [comment] 2023-01-25 13:48
@SandeepJoel Could it be that you type in the letters for the yellow shortcuts without holding down the shift key. I thought I had the same issue, but then I read the manual.. 
Also, apparently you do not have to hold the shift key when selecting items from the top menu bar. So that is a bit inconsistent
Personally I find the need of having to hold down the shift key a bit of a nuisance.

**Comment by dexterleng** [comment] 2023-01-27 14:27
@gerardjanssen

> Also, apparently you do not have to hold the shift key when selecting items from the top menu bar. So that is a bit inconsistent

Hmmm this isn't the intended behaviour - you HAVE to hold Shift to select items via labels.

**Comment by SandeepJoel** [comment] 2023-01-27 14:47
Thanks a ton @dexterleng @gerardjanssen for pointing this out. Next time I will read the manual properly. Sorry for the inconveniences

**Comment by dexterleng** [comment] 2023-01-27 14:56
@SandeepJoel Hey nothing to apologize for - I don't expect everyone to read the docs, especially just to get started using Homerow. Onboarding experience could be better! There should be a better visual clue that the labels are to be typed in caps 🤔

**Comment by dexterleng** [comment] 2023-01-27 14:57
Anyways I'll close this issue now. Thanks for surfacing a UX issue!

**Closed by dexterleng** 2023-01-27 14:57 UTC
Labels: bug
