### ISSUE TITLE
Firefox clickable element detection

### ISSUE THREAD

**Issue by hffmnn** [dexterleng/homerow#19] opened 2022-12-17 19:37 UTC
**Describe the bug**

Coming from version `Beta 0.3.8` the detection for clickable elements in Firefox in `alpha 11` is not very convincing. I often had the case that Homerow had better link detection than Vimium, so it would be super helpful to get this working again.

Is this a known issue for apps like Firefox? The Beta version used to have this voice-over workaround for Firefox.

**Screenshots / video**

`Beta 0.3.8` - Tabs

<img width="611" alt="Screenshot 2022-12-17 at 20 22 09" src="https://user-images.githubusercontent.com/352753/208263218-c4fd1684-3e72-4add-9d35-baadeefc59e1.png">

`alpha 11` - Tabs

<img width="613" alt="Screenshot 2022-12-17 at 20 20 55" src="https://user-images.githubusercontent.com/352753/208263222-74e3d45b-e386-4ba2-a9e5-372b65780463.png">

`Beta 0.3.8` - Links

<img width="665" alt="Screenshot 2022-12-17 at 20 32 44" src="https://user-images.githubusercontent.com/352753/208263286-3e4e3133-ee2c-45cc-aab3-7dc79cea2133.png">

`alpha 11` - Links

<img width="576" alt="Screenshot 2022-12-17 at 20 32 33" src="https://user-images.githubusercontent.com/352753/208263303-38005549-e294-4c6d-86d1-7f7ad8966150.png">

**Steps to reproduce the bug**

1. Open Firefox
2. Click Homerow Shortcut

**Comment by dexterleng** [comment] 2022-12-18 02:08
Firefox isn't supported right now, planning on supporting it soon! App Support is my main priority now.

**Comment by hffmnn** [comment] 2022-12-18 10:33
Ok, thanks a lot for the info. Do you want to keep this issue open as a reference? Or close it?

**Comment by dexterleng** [comment] 2023-01-09 05:14
@hffmnn Hey I just added experimental Firefox support in Alpha 14. 

It's not perfect, I've discovered two issues I'll be working on - (1) GitHub.dev and (2) Gmail's New Message box aren't labelled.

Let me know your thoughts!

**Comment by dexterleng** [comment] 2023-01-09 13:47
Alright, closing this issue now. Please reopen if it doesn't work!

**Closed by dexterleng** 2023-01-09 13:47 UTC
Labels: app support

**Comment by MahdiNazemi** [comment] 2023-03-12 06:34
Hi Dexter,
Would it be possible to share a photo or screen recording of the expected behavior of Homerow in Firefox?
I only get labels for the Close, Minimize, and Maximize buttons.

I come from Vimac, where I remember [we previously had a discussion about Firefox support](https://github.com/dexterleng/vimac/issues/424) and the bug you had filed with Mozilla.
Your earlier message in this thread says that experimental support was added in Alpha 14, and I'm running Alpha 18.
So I'm a little confused about the expected behavior of Homerow in Firefox.

Are there any settings that should be enabled/disabled in Firefox?

Thanks!

**Comment by MahdiNazemi** [comment] 2023-03-12 07:02
It looks like I had set `accessibility.force_disabled` to 1 at some point. Resetting it back to 0 shows labels everywhere in Firefox.
