### ISSUE TITLE
Any better solution for multiple displays

### ISSUE THREAD

**Issue by k1ngcyk** [dexterleng/homerow#44] opened 2023-03-01 09:34 UTC
**Is your feature suggestion related to a problem? Please describe.**
Labels only show on the display where the current activate window is.

**Describe the solution you'd like**
Some shortcuts can robbin macOS's mouse or activate windows through multiple displays.

**Describe alternatives you've considered**
Show some labels for switching the current app's multiple windows.

**Comment by dexterleng** [comment] 2023-03-01 14:29
@k1ngcyk consider trying the apps listed here https://github.com/dexterleng/homerow/issues/11#issuecomment-1356626076. Closing as it's a duplicate of #11.

**Closed by dexterleng** 2023-03-01 14:29 UTC
Labels: enhancement
